name: publish

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r7kamura/weneedfeed-action@v3
        with:
          base_url: https://ya0201.github.io/my-weneedfeed-takeshobo-manga
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
